### ISSUE TITLE
tag manager operator UI bugs and flow updates

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/reaction-admin#150]
### **Flow updates**
Invision prototype: https://invis.io/VRQ0PIFA5CY

**Create flow**
- [ ] Instead of sending the operator to “Edit mode” initially to create a tag, a tag can be created within a card that opens above the Tag table. The operator can either “Save” the tag after entering the name (closing the card and creating the tag), or “Save and add details,” which will create the tag and send the operator to the Edit flow where they can add more details. Mock: http://zpl.io/bWg6Yon
- [ ] The Display title should be autopopulated with the tag name by default when a tag is created. The operator can change this in the Edit mode. Mock: http://zpl.io/and5KDr
- [ ] New tags should be hidden from the storefront by default.

**Edit mode**
- [ ] All three tabs (Tag details, Metadata, Products) should be shown by default. The Products tab can show an empty table with “No products to show” text. Mock: http://zpl.io/aNK606e
- [ ] The "Save" button has been moved out of the cards. http://zpl.io/2pnAlnl

### **UI Bugs/updates**
- [x]  Check marks in table aren't using our design system checks (http://zpl.io/bzYjeKA) reactioncommerce/reaction#4933
- [x]  Edit buttons (pencil icon) are left aligned in column and should be centered reactioncommerce/reaction#4933
- [x]  The visible/hidden column should have a header label = "Status" reactioncommerce/reaction#4933
- [x]  Status column - Hidden status dots should be grey not red, red connotes error reactioncommerce/reaction#4933
- [ ]  Bulk actions button should be enabled - so the user can click it for context (before having anything selected). If they try to take an action w/out anything selected then we should show a warning error saying "No items selected"
- [x]  The status and the action dropdown need to be consistent in their wording (ie make visible/hidden vs enable/disable) reactioncommerce/reaction#4933
