### ISSUE TITLE
[EPIC] De-meteorization

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#7]
This epic is to track the remaining components of the admin application that need to be de-meteorized.

## General Checklist

- [ ] Does it import anything from `/client`
- [ ] Does it import anything from `/lib`
- [ ] Does it have Trackers or composeWithTracker
- [ ] Does it use pub/sub
- [ ] Does it have Meteor method calls
- [ ] Is it straight-up blaze
- [ ] Is it 100% GQL
- [ ] Does it use components from the `ui` package
- [ ] Does it depend on `less css`, or the default theme
- [ ] Does it import meteor packages

### Big

- [x] #68 **[demetorization][big]** Products Admin (included/product-admin)

### Blaze
- [x] #53 **[demetorization][blaze]** Payments (core/payments)
- [x] #67 **[demetorization][blaze]** Payments Stripe (included/payments-stripe)
- [ ] #74 **[demetorization][blaze]** Tax Rates (included/taxes-rates)

### General efforts
- [ ] #33 **[demetorization]** Accounts (core/accounts)
- [ ] #34 **[demetorization]** Address (core/address)
- [ ] #35 **[demetorization]** Catalog (core/catalog)
- [ ] #40 **[demetorization]** Dashboard (core/dashboard)
- [ ] #41 **[demetorization]** Discounts (core/discounts)
- [ ] #42 **[demetorization]** Email (core/email)
- [ ] #43 **[demetorization]** Files (core/files) (1 file)
- [ ] #44 **[demetorization]** GraphQL (core/graphql)
- [x] #47 **[demetorization]** Hydra (core/hydra-oauth)
- [x] #48 **[demetorization]** i18n (core/i18n)
- [x] #49 **[demetorization]** inventory (core/inventory)
- [x] #51 **[demetorization]** Navigation (core/navigation)
- [x] #52 **[demetorization]** Orders (core/orders)
- [x] #55 **[demetorization]** Shipping (core/shipping)
- [x] #56 **[demetorization]** Tags (core/tags)
- [ ] #57 **[demetorization]** Taxes (core/taxes)
- [x] #58 **[demetorization]** Templates (core/templates) (this is email templates)
- [x] #63 **[demetorization]** Discount Codes (included/discount-codes)
- [x] #64 **[demetorization]** Email SMTP (included/email-smtp)
- [x] #66 **[demetorization]** Payments Example (included/payments-example)
- [x] #71 **[demetorization]** Shipping Rates (included/shipping-rates)
- [x] #72 **[demetorization]** Simple Inventory (included/simple-inventory)
- [x] #73 **[demetorization]** Sitemap Generator (included/sitemap-generator)

### Straight-up delete
- [x] #69 **[demetorization][delete]** Products Detail Simple (included/product-detail-simple)
- [ ] #36 **[demetorization][delete]** Checkout (core/checkout)
- [x] #70 **[demetorization][delete][after/during #68]** Product Variant (included/product-variant)
- [ ] #61 **[demetorization][delete]** UI Tagnav (core/ui-tagnav) (PR #75)
- [ ] #60 **[demetorization][delete]** UI Navbar (core/ui-navbar) (PR #75)
- [x] #54 **[demetorization][delete]** Router (core/router)
- [x] #65 **[demetorization][delete??]** Notifications (included/notifications)

### Do these last, probably
- [ ]  #9 **[demetorization][last]** Meteor "Match" errors in terminal
- [ ] #39 **[demetorization][last]** Core (core/core)
- [ ] #37 **[demetorization][last]** Components (core/components)
- [x] #59 **[demetorization][last][delete]** UI (core/ui)
- [x] #50 **[demetorization][last][delete]** Layout (core/layout)
- [x] #62 **[demetorization][last][delete]** Default Theme (included/default-theme)

**Comment by Vercryger** [comment]
Is there any progress of this at all?
